import Foundation
import CryptoKit

/// Pure-function helpers for the §3.2 "auto-tmux on connect" flow.
///
/// On every successful SSH connect (with the per-host `autoTmux`
/// preference enabled), Tessera sends a single shell one-liner over
/// stdin that either:
///
///   - creates the session with a plain detached client
///     (`tmux new-session -d -s <name>`) when it doesn't exist yet, then
///     `exec`s `tmux -CC attach -t <name>`, so control mode always talks
///     to a server that is already up;
///   - `exec`s the same `tmux -CC attach -t <name>` directly when the
///     session already exists, so the user resumes their work
///     transparently;
///   - prints `startFailedSentinel` if tmux is present but the session
///     could not be created — the server failed to start; or
///   - prints `unavailableSentinel` if `tmux` isn't on `$PATH` at all,
///     which Tessera detects in the output stream and surfaces as a
///     dismissible "tmux not available" banner.
///
/// The create-then-attach split is deliberate. `tmux -CC new` has to
/// start the server *and* speak control mode on the same client: when
/// the server cannot come up, that client exits without ever writing the
/// DCS prologue, and the app is left waiting for a handshake that will
/// never arrive (the "stuck at starting tmux on a freshly added host"
/// report — which cured itself for good once any other connection had
/// left a server running). A plain `new-session -d` reports that failure
/// as ordinary shell output instead.
///
/// `exec` is intentional on the happy path: when tmux exits, the
/// login shell exits with it, so disconnect becomes one clean event
/// rather than a return-to-shell-prompt with an orphan process.
///
/// All helpers are pure functions — no UIKit, no SwiftUI, no IO —
/// so they can live in this package and be exhaustively unit-tested
/// without a simulator.
public enum AutoTmuxScript {

    /// Build a tmux client command that requests `ignore-size` only when the
    /// remote tmux version supports the flag (3.2+). Older servers still get
    /// the same attach/new-session operation, without geometry isolation.
    ///
    /// `tmuxCommand` contains the executable, global flags, and subcommand;
    /// `arguments` contains the remaining subcommand arguments. Both are
    /// generated by Tessera rather than accepted from user input.
    public static func geometryPreservingClientCommand(
        tmuxCommand: String,
        arguments: String
    ) -> String {
        let probe = "tessera_tmux_v=$(tmux -V 2>/dev/null); "
            + "tessera_tmux_v=${tessera_tmux_v#tmux }; "
            + "tessera_tmux_major=${tessera_tmux_v%%.*}; "
            + "tessera_tmux_tail=${tessera_tmux_v#*.}; "
            + "tessera_tmux_minor=${tessera_tmux_tail%%[!0-9]*}; "
            + "case \"$tessera_tmux_major:$tessera_tmux_minor\" in "
            + "*[!0-9:]*|:*|*:) tessera_tmux_ignore_size=0 ;; "
            + "*) if [ \"$tessera_tmux_major\" -gt 3 ] || "
            + "{ [ \"$tessera_tmux_major\" -eq 3 ] && [ \"$tessera_tmux_minor\" -ge 2 ]; }; "
            + "then tessera_tmux_ignore_size=1; else tessera_tmux_ignore_size=0; fi ;; "
            + "esac; "
        return probe
            + "if [ \"$tessera_tmux_ignore_size\" = 1 ]; then "
            + "exec \(tmuxCommand) -f ignore-size \(arguments); "
            + "else exec \(tmuxCommand) \(arguments); fi"
    }

    /// Marker the no-tmux branch prints to stdout. Tessera scans the
    /// SSH output stream for this byte sequence (see
    /// `chunkContainsSentinel(_:)`) and shows the unavailable banner
    /// when it appears.
    ///
    /// **The byte sequence the scanner looks for is the INTERPRETED
    /// printf output, not the source string.** The actual shell
    /// command embeds the underscores as octal escapes (`\137` =
    /// `0x5f` = `_`) so that when the PTY echoes the command line
    /// back to us before the shell executes it, the echoed bytes
    /// contain `\137\137TESSERA_NO_TMUX\137\137` — which does NOT
    /// match this needle and therefore doesn't false-positive the
    /// banner. Only the printf's interpreted output matches.
    ///
    /// The two leading and trailing underscores plus the all-caps
    /// `TESSERA_NO_TMUX` make this distinctive enough that we don't
    /// expect false positives in any real shell output either.
    public static let unavailableSentinel = "__TESSERA_NO_TMUX__"

    /// Marker printed when `tmux` exists but the session could not be
    /// brought up — the server refused to start (bad socket directory,
    /// fatal `~/.tmux.conf` error, exhausted resources) or `new-session`
    /// failed for any other reason.
    ///
    /// This exists because the control-mode client is a dead end for
    /// diagnosis: `tmux -CC new` on a host that cannot start a server
    /// exits without ever emitting the DCS prologue, which used to leave
    /// the app waiting on a prologue that was never coming. Creating the
    /// session with a *plain* client first means the failure is an
    /// ordinary shell error we can both show and detect.
    ///
    /// Escaped the same way as `unavailableSentinel` so the PTY echo of
    /// the command line cannot false-positive the scanner.
    public static let startFailedSentinel = "__TESSERA_TMUX_START_FAILED__"

    /// Marker printed when the command runs *inside* an existing tmux
    /// client — the host's own login dotfiles ran `exec tmux` before our
    /// one-liner reached the shell, so `$TMUX` is already set.
    ///
    /// Attaching in control mode from there is impossible (tmux refuses
    /// to nest, and `exec`ing the refusal kills the login shell and the
    /// connection with it). Reporting instead lets the app drop the
    /// launch shield and render the session the host already started as
    /// a normal terminal.
    public static let nestedSentinel = "__TESSERA_TMUX_NESTED__"

    /// Build the one-line shell snippet to send over stdin on connect.
    ///
    /// The leading `clear` wipes the login shell's MOTD and the echoed
    /// command itself, so on the happy path the user sees a clean
    /// terminal hand off straight to tmux's first paint with no
    /// visual gunk. On the failure path the screen is cleared and
    /// then the sentinel + a fresh prompt appear — also clean.
    ///
    /// The sentinel uses POSIX-printf octal escapes (`\137` for `_`)
    /// rather than literal underscores. Why: the PTY echoes the
    /// command line we sent back to us before the shell executes
    /// it. If the source command contained the literal string
    /// `__TESSERA_NO_TMUX__`, our chunk scanner would find it in
    /// the echo and false-positive the banner *before* the shell
    /// even decides whether tmux is available. With escapes, the
    /// echo contains `\137\137TESSERA_NO_TMUX\137\137` (literal
    /// backslash-one-three-seven sequences) which doesn't match
    /// the needle; only the printf's *interpreted* output matches.
    ///
    /// The shell-quoting is fragile-by-design: `<sessionName>` is NOT
    /// shell-escaped, so the caller must constrain it to a known-safe
    /// character set. The session names this package generates via
    /// `defaultSessionName(forHostKey:)` are always
    /// `tessera-[0-9a-f]{8}`, which is safe in any shell.
    public static func command(
        sessionName: String,
        preserveExistingGeometry: Bool = false
    ) -> String {
        let s = sessionName
        let attachCommand: String
        if preserveExistingGeometry {
            attachCommand = geometryPreservingClientCommand(
                tmuxCommand: "tmux -CC attach",
                arguments: "-t \(s)"
            )
        } else {
            attachCommand = "exec tmux -CC attach -t \(s)"
        }
        return "export COLORTERM=truecolor; clear; "
            + "if [ -n \"$TMUX\" ]; then printf '\\137\\137TESSERA_TMUX_NESTED\\137\\137\\n'; "
            + "elif command -v tmux >/dev/null 2>&1; then "
            + "if tmux has-session -t \(s) 2>/dev/null || tmux new-session -d -s \(s); then "
            + "\(attachCommand); "
            + "else printf '\\137\\137TESSERA_TMUX_START_FAILED\\137\\137\\n'; "
            + "fi; "
            + "else printf '\\137\\137TESSERA_NO_TMUX\\137\\137\\n'; "
            + "fi\n"
    }

    /// Derive a deterministic 8-hex-char tmux session name from a
    /// host identifier (e.g. `"user@host:port"`).
    ///
    /// Same input always yields the same name, so two consequences
    /// fall out for free:
    ///
    /// 1. **Reinstalls don't accumulate orphans.** If the user wipes
    ///    Tessera's local state, a fresh app talking to the same host
    ///    computes the same name and re-attaches to the existing
    ///    server-side tmux session instead of stranding it.
    ///
    /// 2. **Two devices using the same Host config rendezvous.**
    ///    iPad A and iPad B with the same `user@host:port` end up
    ///    sharing one tmux session, which is exactly what most users
    ///    expect from a "resume my work" feature across devices.
    ///
    /// SHA-256 → first 4 bytes → 8 hex chars is more than enough
    /// uniqueness for the per-host scope (collisions matter only
    /// when two different host-keys collide, and the birthday-bound
    /// is ~65k pairs).
    public static func defaultSessionName(forHostKey key: String) -> String {
        return "tessera-\(shortDigest(of: key))"
    }

    /// Log-safe token for a tmux session name: `sessionNameDigest("acme-prod")`
    /// → `"1f3a9c02"`.
    ///
    /// A session name is the only stable identity in the launch path. The
    /// per-view `sid=` correlates lines inside one launch attempt and nothing
    /// beyond it — not a reconnect, not an app restart, not two reports from the
    /// same user. Redacting the name would collapse every session to one token
    /// and destroy exactly the correlation the field exists for, so it is
    /// hashed instead: deterministic, so the same session yields the same token
    /// everywhere; 32 bits, so the handful of sessions a user runs stay
    /// distinguishable.
    ///
    /// **Every diagnostic that names a tmux session must call this.** Two
    /// independent derivations would silently mint two tokens for one session,
    /// which is worse than having no token at all.
    ///
    /// In auto mode the name is already `tessera-<8 hex of host key>`, so
    /// hashing again is lossless for correlation and additionally keeps the
    /// host-key digest itself out of the log.
    public static func sessionNameDigest(_ name: String) -> String {
        shortDigest(of: name)
    }

    private static func shortDigest(of input: String) -> String {
        let digest = SHA256.hash(data: Data(input.utf8))
        return digest.prefix(4).map { String(format: "%02x", $0) }.joined()
    }

    /// Returns true if the chunk's bytes contain the unavailable
    /// sentinel anywhere in their interior.
    ///
    /// Naive O(n·m) substring scan: the needle is 19 bytes and a
    /// typical SSH chunk is a few KB, so even pessimistically this
    /// is microsecond-scale work; Boyer–Moore would be overkill.
    ///
    /// This is intentionally stateless. Use `AutoTmuxSentinelScanner`
    /// when scanning a byte stream where the sentinel may cross chunk
    /// boundaries.
    public static func chunkContainsSentinel(_ chunk: [UInt8]) -> Bool {
        contains(Array(unavailableSentinel.utf8), in: chunk)
    }

    /// Same naive scan, for an arbitrary marker.
    static func contains(_ needle: [UInt8], in chunk: [UInt8]) -> Bool {
        guard !needle.isEmpty, chunk.count >= needle.count else { return false }
        outer: for i in 0...(chunk.count - needle.count) {
            for j in 0..<needle.count where chunk[i + j] != needle[j] {
                continue outer
            }
            return true
        }
        return false
    }
}

/// Which failure marker the auto-tmux script printed, if any.
public enum AutoTmuxFailure: Equatable, Sendable {
    /// `tmux` is not on the remote `$PATH`.
    case unavailable
    /// `tmux` exists but the session could not be created.
    case startFailed
    /// The host's own dotfiles already put us inside a tmux client.
    case nested
}

/// Streaming detector for `AutoTmuxScript.unavailableSentinel`.
///
/// Session output usually arrives in packet-sized chunks, but the
/// sentinel is still allowed to straddle a chunk boundary. This scanner
/// keeps just enough tail bytes to make the next feed boundary-safe.
public struct AutoTmuxSentinelScanner {
    private let unavailableNeedle: [UInt8] = Array(
        AutoTmuxScript.unavailableSentinel.utf8
    )
    private let startFailedNeedle: [UInt8] = Array(
        AutoTmuxScript.startFailedSentinel.utf8
    )
    private let nestedNeedle: [UInt8] = Array(
        AutoTmuxScript.nestedSentinel.utf8
    )
    private var tail: [UInt8] = []

    public init() {}

    public mutating func reset() {
        tail.removeAll(keepingCapacity: true)
    }

    /// `true` when the "tmux is not installed" marker appeared. Kept for
    /// call sites that only care about that case.
    public mutating func feed(_ chunk: [UInt8]) -> Bool {
        feedForFailure(chunk) == .unavailable
    }

    /// Scan for either marker, reporting which one landed. The scanner
    /// keeps the longest needle's boundary bytes so a marker split across
    /// two SSH chunks is still detected.
    public mutating func feedForFailure(_ chunk: [UInt8]) -> AutoTmuxFailure? {
        var haystack = tail
        haystack.append(contentsOf: chunk)

        let failure: AutoTmuxFailure?
        if AutoTmuxScript.contains(unavailableNeedle, in: haystack) {
            failure = .unavailable
        } else if AutoTmuxScript.contains(startFailedNeedle, in: haystack) {
            failure = .startFailed
        } else if AutoTmuxScript.contains(nestedNeedle, in: haystack) {
            failure = .nested
        } else {
            failure = nil
        }

        let keepCount = max(
            max(
                unavailableNeedle.count,
                max(startFailedNeedle.count, nestedNeedle.count)
            ) - 1,
            0
        )
        if haystack.count > keepCount {
            tail = Array(haystack.suffix(keepCount))
        } else {
            tail = haystack
        }
        return failure
    }
}
